apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: {{JOB_NAME}}
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: {{IMAGE}}
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/main.py
  arguments:
    - "--mode"
    - "spark"
    - "--stage"
    - "landing"
    - "--source_folder"
    - "/"
    - "--dest_folder"
    - "/spark_output"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    labels:
      version: 3.5.0
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.5.0
